#!/bin/bash
python -m SimpleHTTPServer

# ausführbar machen: chmod a+rwx startServer
# ausführen: ./startServer
# open http://localhost:8000/index.html in Browser

# Quelle: https://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local/21608670
