export const CHANGE_GRAPH = "CHANGE_GRAPH";

export const CHECKBOX_FILTER_CHANGE = "CHECKBOX_FILTER_CHANGE";
export const TIMERANGE_FILTER_CHANGE = "TIMERANGE_FILTER_CHANGE";

export const PROJECT_HOVERED = "PROJECT_HOVERED";
export const CAT_HOVERED = "CAT_HOVERED";
export const INFRA_HOVERED = "INFRA_HOVERED";
export const KTA_HOVERED = "KTA_HOVERED";
export const YEAR_HOVERED = "YEAR_HOVERED";
export const UNHOVERED = "UNHOVERED";

export const PROJECT_CLICKED = "PROJECT_CLICKED";
export const CAT_CLICKED = "CAT_CLICKED";
export const INFRA_CLICKED = "INFRA_CLICKED";
export const KTA_CLICKED = "KTA_CLICKED";
export const YEAR_CLICKED = "YEAR_CLICKED";
export const UNCLICKED = "UNCLICKED";

export const SHOW_UNCERTAINTY = "SHOW_UNCERTAINTY";
export const HIGHLIGHT_UNCERTAINTY = "HIGHLIGHT_UNCERTAINTY";
export const LEGEND_HOVERED = "LEGEND_HOVERED";

export const UPDATE_KTA_MAPPING_DATA = "UPDATE_KTA_MAPPING_DATA";
export const UPDATE_TARGETGROUPS_DATA = "UPDATE_TARGETGROUPS_DATA";
export const UPDATE_INFRASTRUCTURE_DATA = "UPDATE_INFRASTRUCTURE_DATA";
export const UPDATE_COLLECTIONS_DATA = "UPDATE_COLLECTIONS_DATA";
export const UPDATE_PROJECTS_DATA = "UPDATE_PROJECTS_DATA";
export const UPDATE_KTA_DATA = "UPDATE_KTA_DATA";
export const UPDATE_CLUSTER_DATA = "UPDATE_CLUSTER_DATA";
export const UPDATE_INSTITUTIONS_DATA = "UPDATE_INSTITUTIONS_DATA";

export const TOUR_STARTED = "TOUR_STARTED";
export const TUTORIAL_STARTED = "TUTORIAL_STARTED";
export const PAGE_RESET = "PAGE_RESET";
export const SHARE_DIALOG_OPENED = "SHARE_DIALOG_OPENED";
export const SHOW_VIA_WIKI_REQUESTED = "SHOW_VIA_WIKI_REQUESTED";

export const PROCESS_DATA_IF_READY = "PROCESS_DATA_IF_READY";
